name: Latest blog post workflow
on:
    schedule: # Run workflow automatically
        - cron: "0 */12 * * *" # Runs every 12 hours
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
    contents: write # To write the generated contents to the readme

jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Pull in portfolio website posts
              uses: gautamkrishnar/blog-post-workflow@v1
              with:
                  feed_list: "https://aliabb.vercel.app/blog/rss.xml"
                  max_post_count: 5
                  commit_message: "Updated profile readme with the latest blog posts"
